[package]
name = "ferox"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.1", features = ["rt-multi-thread", "macros"] }
toml = "1.1.2"
futures = "0.3"
serde_json = "1.0.149"
reqwest = { version = "0.13.3", features = ["stream"] }
error = "0.1.9"
async-stream = "0.3.6"
futures-core = "0.3.32"
futures-util = "0.3.32"
http = "1.4.1"
